In [4]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)

from datetime import datetime
from datetime import date

In [2]:
df_model = pd.read_csv("../inter_data/processed_data.csv")
df_model = df_model[[col for col in df_model.columns if "Unnamed" not in col]]

FileNotFoundError: [Errno 2] No such file or directory: '../inter_data/processed_data.csv'

In [50]:
df_model["target"] = pd.qcut(df_model["target"], 12, duplicates='drop')

In [52]:
target_bins = list(df_model["target"].value_counts().index )
target_bins.sort()
df_model["target2"] = [""]*len(df_model["target"])
for i, b in enumerate(target_bins):
    df_model.loc[df_model["target"] == b, "target2"] = i + 1

del df_model["target"]

In [51]:
df_model["target"].value_counts()

(-0.001, 0.333]    25556
(0.592, 1.0]        5563
(0.333, 0.592]      2265
(1.0, 2.0]             2
Name: target, dtype: int64

In [54]:
df_model

,IncomePA,IsKarvy,KRA YN,age,months_since_last_login,months_since_last_trade,total_logins_one_year,total_trades_one_year,referees_avg_logins_in_last_year,referees_avg_trades_in_last_year,E2Channel_CAT,E2Channel_Franchisee,E2Channel_GL Investments,E2Channel_Premia,E2Channel_others,cm_occup_Agriculturist,cm_occup_B,cm_occup_Business,cm_occup_F,cm_occup_Gov. Service,cm_occup_H,cm_occup_House Wife,cm_occup_Housewife,cm_occup_O,cm_occup_Other,cm_occup_P,cm_occup_PRIVATE SECTOR,cm_occup_Private Sector,cm_occup_Professional,cm_occup_Public Sector,cm_occup_R,cm_occup_Retired,cm_occup_S,cm_occup_SALARIED,cm_occup_SELF EMPLOYED,cm_occup_ST,cm_occup_Student,target2
0,4.0,0,0,-0.573815,-0.446993,1.535000,-0.282612,-0.108067,0.000000,0.000000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
1,1.0,0,1,-0.573815,-0.466846,-0.658285,-0.259869,-0.106695,0.000000,0.000000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
2,1.0,0,0,-0.573815,-0.460685,-0.666017,-0.288070,-0.106695,0.000000,0.000000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
3,1.0,0,0,0.497885,-0.477800,-0.630670,-0.102493,-0.101209,-0.205539,-0.079809,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,3
4,1.0,0,1,-0.466645,-0.462739,-0.639506,-0.228940,-0.106695,0.000000,0.000000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33381,1.0,0,0,-0.037965,2.266210,1.535000,-0.291709,-0.108067,0.000000,0.000000,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
33382,3.0,0,0,0.926564,-0.477800,-0.674854,0.951835,0.292403,0.000000,0.000000,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
33383,1.0,0,0,-0.252305,-0.477800,-0.674854,1.195632,-0.021664,0.722847,0.368573,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,3
33384,4.0,0,0,0.605055,-0.477800,-0.661599,0.054883,-0.051836,-0.123787,-0.073790,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,3
33385,1.0,0,0,1.033734,-0.389485,1.535000,-0.282612,-0.108067,-0.140464,-0.090674,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1

## Catboost

In [11]:
df_model = pd.read_csv("../inter_data/processed_catboost.csv")

df_model = df_model[[col for col in df_model.columns if "Unnamed" not in col]]

In [12]:
df_model["target"] = pd.qcut(df_model["target"], 12, duplicates='drop')

target_bins = list(df_model["target"].value_counts().index )
target_bins.sort()
df_model["target2"] = [""]*len(df_model["target"])
for i, b in enumerate(target_bins):
    df_model.loc[df_model["target"] == b, "target2"] = i + 1

del df_model["target"]

df_model["target2"].value_counts()

1    25556
3     5563
2     2265
4        2
Name: target2, dtype: int64

In [13]:
df_model.rename(columns = {"target2": "target"}, inplace = True)

In [14]:
df_model.describe()

,IsKarvy,age,months_since_last_login,months_since_last_trade,total_logins_one_year,total_trades_one_year,referees_avg_logins_in_last_year,referees_avg_trades_in_last_year
count,33386.000000,33386.000000,33386.000000,33386.000000,33386.000000,33386.000000,33386.000000,33386.000000
mean,0.010154,27.354250,23.242926,40.687815,320.668693,78.796142,33.920889,5.127310
std,0.100255,9.331117,47.991441,59.487637,1099.293999,729.154607,289.271553,91.736713
min,0.000000,1.000000,0.312963,0.312963,0.000000,0.000000,0.000000,0.000000
25%,0.000000,21.000000,0.345818,0.970060,5.000000,0.000000,0.000000,0.000000
50%,0.000000,24.000000,1.101480,1.988562,21.000000,1.000000,0.000000,0.000000
75%,0.000000,31.000000,5.734019,132.000000,90.000000,3.000000,3.000000,1.000000
max,1.000000,121.000000,132.000000,176.053738,53532.000000,89876.000000,17268.000000,8461.000000

In [15]:
pd.DataFrame(df_model.nunique()).rename(columns = {0: "num_unique"})

                                  num_unique
IncomePA                                   9
cm_occup                                  23
E2Channel                                 12
IsKarvy                                    2
KRA YN                                     2
age                                       78
months_since_last_login                  663
months_since_last_trade                  486
total_logins_one_year                   2972
total_trades_one_year                   1318
referees_avg_logins_in_last_year        1490
referees_avg_trades_in_last_year         663
target                                     4

In [16]:
cat_features = ["KRA YN", "IsKarvy", "cm_occup", "IncomePA", "E2Channel"]
df_model["IsKarvy"] = df_model["IsKarvy"].astype(int)

df_model = df_model.dropna()

X = df_model.drop("target", axis=1)
y = df_model["target"]

In [17]:

# train test split
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.1, random_state=0)

In [19]:



from catboost import CatBoostClassifier

cat_clf = CatBoostClassifier(
    iterations=50,
    random_seed=42,
    learning_rate=0.5,
    custom_loss=['AUC', 'Accuracy', 'Recall'], 
    loss_function='MultiClass'
    
)


cat_clf.fit(
    X_train, y_train,
    cat_features=cat_features,
    eval_set=(X_val, y_val),
    verbose=True,
    plot=True, 
    
)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.5725669	test: 0.5625201	best: 0.5625201 (0)	total: 85.4ms	remaining: 4.18s
1:	learn: 0.4422313	test: 0.4302107	best: 0.4302107 (1)	total: 106ms	remaining: 2.54s
2:	learn: 0.3779989	test: 0.3631422	best: 0.3631422 (2)	total: 128ms	remaining: 2s
3:	learn: 0.3411104	test: 0.3266575	best: 0.3266575 (3)	total: 147ms	remaining: 1.7s
4:	learn: 0.3208778	test: 0.3049896	best: 0.3049896 (4)	total: 168ms	remaining: 1.51s
5:	learn: 0.3100456	test: 0.2937101	best: 0.2937101 (5)	total: 191ms	remaining: 1.4s
6:	learn: 0.3033269	test: 0.2877399	best: 0.2877399 (6)	total: 212ms	remaining: 1.3s
7:	learn: 0.2984577	test: 0.2840057	best: 0.2840057 (7)	total: 232ms	remaining: 1.22s
8:	learn: 0.2959827	test: 0.2827008	best: 0.2827008 (8)	total: 251ms	remaining: 1.14s
9:	learn: 0.2935265	test: 0.2800099	best: 0.2800099 (9)	total: 273ms	remaining: 1.09s
10:	learn: 0.2924823	test: 0.2799370	best: 0.2799370 (10)	total: 295ms	remaining: 1.04s
11:	learn: 0.2918932	test: 0.2796246	best: 0.2796246 (11)	total: 312ms	remaining: 988ms
12:	learn: 0.2913030	test: 0.2793540	best: 0.2793540 (12)	total: 332ms	remaining: 946ms
13:	learn: 0.2906687	test: 0.2792559	best: 0.2792559 (13)	total: 351ms	remaining: 902ms
14:	learn: 0.2886549	test: 0.2780223	best: 0.2780223 (14)	total: 368ms	remaining: 859ms
15:	learn: 0.2881333	test: 0.2782415	best: 0.2780223 (14)	total: 387ms	remaining: 823ms
16:	learn: 0.2874452	test: 0.2781203	best: 0.2780223 (14)	total: 406ms	remaining: 788ms
17:	learn: 0.2863806	test: 0.2775192	best: 0.2775192 (17)	total: 425ms	remaining: 755ms
18:	learn: 0.2851214	test: 0.2770187	best: 0.2770187 (18)	total: 444ms	remaining: 724ms
19:	learn: 0.2845675	test: 0.2768222	best: 0.2768222 (19)	total: 463ms	remaining: 695ms
20:	learn: 0.2837441	test: 0.2766486	best: 0.2766486 (20)	total: 480ms	remaining: 663ms
21:	learn: 0.2833464	test: 0.2767967	best: 0.2766486 (20)	total: 501ms	remaining: 638ms
22:	learn: 0.2829317	test: 0.2768603	best: 0.2766486 (20)	total: 521ms	remaining: 611ms
23:	learn: 0.2813334	test: 0.2776133	best: 0.2766486 (20)	total: 540ms	remaining: 585ms
24:	learn: 0.2799810	test: 0.2767804	best: 0.2766486 (20)	total: 559ms	remaining: 559ms
25:	learn: 0.2795059	test: 0.2769632	best: 0.2766486 (20)	total: 580ms	remaining: 535ms
26:	learn: 0.2791155	test: 0.2770982	best: 0.2766486 (20)	total: 600ms	remaining: 511ms
27:	learn: 0.2781039	test: 0.2767544	best: 0.2766486 (20)	total: 620ms	remaining: 487ms
28:	learn: 0.2779335	test: 0.2767978	best: 0.2766486 (20)	total: 640ms	remaining: 464ms
29:	learn: 0.2775678	test: 0.2765452	best: 0.2765452 (29)	total: 662ms	remaining: 441ms
30:	learn: 0.2767887	test: 0.2772315	best: 0.2765452 (29)	total: 681ms	remaining: 418ms
31:	learn: 0.2762596	test: 0.2772174	best: 0.2765452 (29)	total: 700ms	remaining: 394ms
32:	learn: 0.2759591	test: 0.2773079	best: 0.2765452 (29)	total: 722ms	remaining: 372ms
33:	learn: 0.2758117	test: 0.2771964	best: 0.2765452 (29)	total: 743ms	remaining: 350ms
34:	learn: 0.2751391	test: 0.2767660	best: 0.2765452 (29)	total: 764ms	remaining: 327ms
35:	learn: 0.2748705	test: 0.2768365	best: 0.2765452 (29)	total: 784ms	remaining: 305ms
36:	learn: 0.2744866	test: 0.2769952	best: 0.2765452 (29)	total: 803ms	remaining: 282ms
37:	learn: 0.2741277	test: 0.2769121	best: 0.2765452 (29)	total: 823ms	remaining: 260ms
38:	learn: 0.2736044	test: 0.2771557	best: 0.2765452 (29)	total: 842ms	remaining: 238ms
39:	learn: 0.2729683	test: 0.2777516	best: 0.2765452 (29)	total: 862ms	remaining: 216ms
40:	learn: 0.2724788	test: 0.2780238	best: 0.2765452 (29)	total: 881ms	remaining: 193ms
41:	learn: 0.2720880	test: 0.2779619	best: 0.2765452 (29)	total: 901ms	remaining: 172ms
42:	learn: 0.2717626	test: 0.2782248	best: 0.2765452 (29)	total: 922ms	remaining: 150ms
43:	learn: 0.2714836	test: 0.2783969	best: 0.2765452 (29)	total: 944ms	remaining: 129ms
44:	learn: 0.2705660	test: 0.2785505	best: 0.2765452 (29)	total: 963ms	remaining: 107ms
45:	learn: 0.2700996	test: 0.2785392	best: 0.2765452 (29)	total: 985ms	remaining: 85.7ms
46:	learn: 0.2696413	test: 0.2782863	best: 0.2765452 (29)	total: 1s	remaining: 64.2ms
47:	learn: 0.2690549	test: 0.2788700	best: 0.2765452 (29)	total: 1.03s	remaining: 42.8ms
48:	learn: 0.2684864	test: 0.2785121	best: 0.2765452 (29)	total: 1.05s	remaining: 21.4ms
49:	learn: 0.2683888	test: 0.2785107	best: 0.2765452 (29)	total: 1.08s	remaining: 0us

bestTest = 0.2765451855
bestIteration = 29

Shrink model to first 30 iterations.

In [142]:
df_model["target"].value_counts()

1    25196
3     5485
2     2240
4        2
Name: target, dtype: int64

## saving model

In [130]:
try:
    !mkdir ../models
except:
    pass
cat_clf.save_model('../models/catboost_classifier')

In [2]:
from catboost import CatBoostClassifier
model = CatBoostClassifier()      # parameters not required.
model.load_model('../models/catboost_classifier')

In [5]:
df_model = pd.read_csv("../inter_data/processed_catboost.csv")
X = df_model.drop(["target"], axis = 1)
y = df_model["target"]

In [6]:
model.predict(X)

CatBoostError: Invalid type for cat_feature[non-default value idx=692,feature_idx=1]=nan : cat_features must be integer or string, real number values and NaN values should be converted to string.

In [7]:
X.isna().sum()

Unnamed: 0                            0
IncomePA                            247
cm_occup                            354
E2Channel                            34
IsKarvy                               0
KRA YN                                0
age                                   0
months_since_last_login               0
months_since_last_trade               0
total_logins_one_year                 0
total_trades_one_year                 0
referees_avg_logins_in_last_year      0
referees_avg_trades_in_last_year      0
dtype: int64